package nexiosit.com.name_generator.constants;

import java.util.Arrays;
import java.util.List;

public class NamingConstants {
    public static List<String> prefixes = Arrays.asList("Insulted",
            "Swore",
            "Trimmed",
            "Pleased",
            "Genius",
            "Adorned",
            "Noticeable",
            "Denied",
            "Deprived",
            "Cynical",
            "Summoned",
            "King",
            "Faithful",
            "Luscious",
            "Blazing",
            "Black",
            "Dangerous",
            "Deflowered",
            "Bathroom",
            "Fast",
            "Passing",
            "Refreshing",
            "Poetic",
            "Supernatural",
            "Undressed",
            "Attentive",
            "Exorcised",
            "Grimacing",
            "Spartan",
            "Stoned",
            "Cuddly",
            "Vulnerable",
            "Charming",
            "Paraded",
            "Childhood",
            "Matronly",
            "Whispering",
            "Open-Air",
            "Jealous",
            "Quiet",
            "Masculine",
            "Fair-Haired",
            "Wonderful",
            "Hungry",
            "Professional",
            "Strolling",
            "True",
            "Fashionable",
            "Off-Shore",
            "Bombed",
            "Dazzling",
            "Lost",
            "Toweling",
            "Double",
            "Deadly",
            "Squirming",
            "Tempered",
            "Soaped",
            "Mimicked",
            "Coastal",
            "Easygoing",
            "Guiltily",
            "Undeniable",
            "Friendly",
            "Terrific",
            "Prodded",
            "Drifting",
            "Uninterested",
            "Miserable",
            "Twenty-Eight-Inch",
            "Smokey",
            "Elite",
            "Chocolate",
            "Dancing",
            "Observing",
            "Old-Fashioned",
            "Social",
            "Transfixed",
            "Unbelievable",
            "Disappointed",
            "Bulging",
            "Amazing",
            "Interrupted",
            "Delighted",
            "Clapping",
            "Stranger",
            "Sudden",
            "Nice-Looking",
            "Reed-Slim",
            "Chocolate-Coated",
            "Submerged",
            "Overweight",
            "Outraged",
            "Drunk",
            "Imaginative",
            "Honey-Blond",
            "Double-Locked",
            "Diverting",
            "Watched",
            "Famous",
            "Transported",
            "Little",
            "Honest-To-Goodness",
            "Green",
            "Thrilled",
            "Walloped",
            "Exhausted",
            "Successful",
            "Stable",
            "Comfortable",
            "Chattering",
            "Arcade",
            "Hooked",
            "Matching",
            "Unlocked",
            "Organized",
            "Threatening",
            "Satisfied",
            "Thumbing",
            "Over-Zealous",
            "Addicted",
            "Chaperone",
            "Lower",
            "Tousled",
            "Prime",
            "Dumb",
            "Gambling",
            "Greedy",
            "Resigned",
            "Chartered",
            "Weaving",
            "Control",
            "Disturbing",
            "Wrapped",
            "Attended",
            "Studied",
            "African",
            "Tiny",
            "Uppity",
            "Touchy",
            "Well-Developed",
            "Decorated",
            "Required",
            "Minimal",
            "Rude",
            "Stacked",
            "Plump",
            "Studying",
            "Middle",
            "Chinese",
            "Surrounded",
            "Mental",
            "Bundled",
            "Jumping",
            "Long-Distance",
            "Uncomplaining",
            "Replacement",
            "Essential",
            "Reasonable",
            "Purple",
            "Confident",
            "Almond-Shaped",
            "Consulted",
            "Touched",
            "Painless",
            "Thrusting",
            "Failed",
            "Slammed",
            "Pressed",
            "Checkered",
            "Determined",
            "Exciting",
            "Kissed",
            "Private",
            "Performing",
            "Pure",
            "Eating",
            "Nagging",
            "Dressed",
            "Incapable",
            "Sensational",
            "Incipient",
            "Adjoining",
            "Jaded",
            "Well-Known",
            "Unsettling",
            "Perfect",
            "Offstage",
            "Strutting",
            "Witty",
            "Requested",
            "Reserved",
            "Oncoming",
            "Plastic",
            "Communal",
            "Wondering",
            "Burning",
            "Waiting",
            "Medicinal",
            "Meticulous",
            "Baby-Faced",
            "Introduced",
            "Scrubbed",
            "Grabbing",
            "Growing",
            "Hundred-Dollar",
            "Pushover",
            "Hitting",
            "Untouched",
            "Daily",
            "Shabby",
            "Middle-Aged",
            "Screaming",
            "Reluctant",
            "Adoring",
            "Rock-Soul",
            "Sulky",
            "Recovered",
            "Startling",
            "Jolly",
            "Rolling",
            "Bold",
            "Unconcealed",
            "Jostling",
            "Persuaded",
            "Luminous",
            "Comfortable",
            "Cleaning",
            "Weekend",
            "Killer",
            "Obscure",
            "Departed",
            "Writer",
            "Uncommunicative",
            "Knowing",
            "Squeezed",
            "Captivated",
            "Secret",
            "Rich",
            "Maniacal",
            "Freaky",
            "Actual",
            "Rehearsed",
            "Tanned",
            "Shouting",
            "Barbecue",
            "Uptight",
            "Slouched",
            "Surveying",
            "Businesslike",
            "Explicit",
            "Heavy",
            "Boisterous",
            "Living",
            "Good-Time",
            "Flattered",
            "Shuttered",
            "Convinced",
            "Pretend",
            "Apologetic",
            "Naked",
            "Inventive",
            "Creeping",
            "Tucked",
            "Sideways",
            "Beginning",
            "Vacant",
            "Enormous",
            "American",
            "Crowded",
            "Stupid",
            "Fluffed",
            "Lurking",
            "Bossing",
            "Virile",
            "Unzipped",
            "Persuasive",
            "Lousy",
            "Dead",
            "Lingering",
            "Permanent",
            "Emotional",
            "Impossible",
            "Interested",
            "Ultimate",
            "Experienced",
            "Door",
            "Winning",
            "Stifled",
            "Fattening",
            "Overlooking",
            "Patterned",
            "Sixteen-Year-Old",
            "Streaming",
            "Leering",
            "Fantasizing",
            "Superstar",
            "Bionic",
            "Featured",
            "Relieved",
            "Affronted",
            "Double-Crossed",
            "Paltry",
            "Chauffeured",
            "Cheesy",
            "Serious",
            "Starry",
            "Washed",
            "Thawing",
            "Fitted",
            "Non-Stop",
            "Pinched",
            "Digital",
            "Duplex",
            "Coincidental",
            "Stubbed",
            "Spluttering",
            "Screening",
            "Tough",
            "Poor",
            "Glossy",
            "Delayed",
            "Protected",
            "Well-Preserved",
            "Ridiculous",
            "Temperamental",
            "Discreet",
            "Marvelous",
            "Brash",
            "Dejected",
            "Suitable",
            "Cursing",
            "Snapping",
            "Straight",
            "Wildlife",
            "Mean-Looking",
            "Fumbling",
            "Skimming",
            "Purchased",
            "Layabout",
            "Handsome",
            "Telephoning",
            "Delicious",
            "Unheard-Of",
            "Penetrating",
            "Occasional",
            "Gangster",
            "White",
            "Regulation",
            "Innocent",
            "Hurried",
            "Suspected",
            "Dreary",
            "Pretty",
            "Lazy",
            "Highway",
            "Casual",
            "Married",
            "Divorced",
            "Staking",
            "Participating",
            "Triggered",
            "Substantial",
            "Taunting",
            "White-Faced",
            "Commanded",
            "Romantic",
            "Attacked",
            "Public",
            "Operation",
            "Luxury",
            "Chewing",
            "Floating",
            "Mixed",
            "Unbeknownst",
            "Sunburned",
            "Disco",
            "Powerless",
            "Sensible",
            "Intimidating",
            "Shower",
            "Baggy",
            "Tenth",
            "Orange",
            "Settled",
            "Blackmailed",
            "Mesmerizing",
            "Aggravating",
            "Happy",
            "Murky",
            "Grueling",
            "Industry",
            "Proud",
            "Roaming",
            "Village",
            "Sly-Faced",
            "Lonely",
            "Random",
            "Uneventful",
            "Furious",
            "Surprising",
            "Strapped",
            "Undressed",
            "Fantastic",
            "So-Called",
            "Thrashing",
            "Ecstatic",
            "Declined",
            "Crucial",
            "Identified",
            "Princess",
            "Trained",
            "Farm",
            "Powdered",
            "Wrong",
            "Green-Taloned",
            "Giggling",
            "Makes",
            "Equipped",
            "Escorted",
            "Half-Hearted",
            "Unhappy",
            "Glowing",
            "Straightfaced",
            "Select",
            "Unqualified",
            "Striking",
            "Embarrassed",
            "Manual",
            "Backstage",
            "Extreme",
            "Divided",
            "Clockwork",
            "Awkward",
            "Peculiar",
            "Second",
            "Clinging",
            "Wide-Mouthed",
            "Drinking",
            "Informed",
            "Tripping",
            "Steady",
            "Greeted",
            "Lucky",
            "Involved",
            "Beautiful",
            "Twenty-Handed",
            "Disgusting’",
            "Strong",
            "Unpacked",
            "Remembered",
            "Unnoticed",
            "Gleaming",
            "Struggling",
            "Desired",
            "Smiling",
            "Petulant",
            "Former",
            "Properly",
            "Warm",
            "Sensitive",
            "Sun-Streaked",
            "Respectable",
            "Used",
            "Awful",
            "Shopping",
            "Emphasized",
            "Twenty-Dollar",
            "Tasty",
            "Sleeping",
            "Intelligent",
            "Battered",
            "Puzzled",
            "Bland",
            "Promised",
            "Tempted",
            "Busy",
            "Choking",
            "Greasy",
            "Singing",
            "Prepared",
            "Replaceable",
            "Breeding",
            "Starved",
            "Sprouted",
            "Arranging",
            "Lucrative",
            "Anxious",
            "Impressed",
            "Shrunken",
            "Listening",
            "Hazy",
            "Devious",
            "Italian",
            "Retching",
            "Ratty",
            "Rubber",
            "Drained",
            "Dynamite",
            "Anticipated",
            "Air-Conditioned",
            "Exclusive",
            "Future",
            "Remote",
            "Possessive",
            "Revealing",
            "Sweating",
            "Tempting",
            "Favourite",
            "Icy",
            "Swarming",
            "Unmoving",
            "Entertained",
            "Spying",
            "Forthcoming",
            "Confiding",
            "Jutting",
            "Rip-Off",
            "Popular",
            "Godawful",
            "Immediate",
            "Out-Of-Town",
            "Intricate",
            "Expensive",
            "Whisking",
            "Independent",
            "Faceless",
            "Fifty-Two-Year-Old",
            "Staggering",
            "Straining",
            "Recent",
            "Boring",
            "Complete",
            "Empty-Handed",
            "Legend",
            "Half-Assed",
            "Grateful",
            "Swaying",
            "Obscene",
            "Lined",
            "Accompanied",
            "Admired",
            "Sellout",
            "Pleasing",
            "Clustered",
            "Anesthetized",
            "Sexy",
            "Huddled",
            "Midnight",
            "Physical",
            "Shuddering",
            "Deformed",
            "Hairdressing",
            "Uncomfortable",
            "Spotlight",
            "Full-Length",
            "Stud",
            "Sizzling",
            "Tear-Filled",
            "Formidable",
            "Juicy",
            "Frightening",
            "Orphan",
            "Scribbled",
            "Panic-Stricken",
            "Garbage",
            "Annoyed",
            "Honest",
            "Neglected",
            "Photographed",
            "Attractive",
            "Immaculate",
            "Captured",
            "Sweet",
            "Unfeeling",
            "Scratching",
            "Dreadful",
            "Bouncing",
            "Untidy",
            "Incredible",
            "Overawed",
            "Cooking",
            "Throaty",
            "Demanding",
            "Pushy",
            "Older",
            "Assistant",
            "Classic",
            "Tight-Lipped",
            "Youngish",
            "Adjectives",
            "Cringing",
            "Wild",
            "Skinny",
            "Ambitious",
            "High-Pitched",
            "Marveling",
            "Bored",
            "Lethal",
            "Strange",
            "Hated",
            "Emerging",
            "Dedicated",
            "Private",
            "Fancy",
            "Streaked",
            "Breathless",
            "Mocking",
            "Redfaced",
            "Lovely",
            "Elaborate",
            "Regarded",
            "Concentrated",
            "Surprised",
            "Collecting",
            "Cruel",
            "Terrible",
            "Spirited",
            "Unblemished",
            "Scrawny",
            "Classy",
            "Tapping",
            "Doubling",
            "Smoking",
            "Huge",
            "Lush",
            "Cheering",
            "Relaxed",
            "Muscled",
            "Sumptuous",
            "Peak",
            "Hustled",
            "Wrinkled",
            "Applauding",
            "Sleepy",
            "Creamy-Looking",
            "Suntanned",
            "Heavenly",
            "Hysterical",
            "Vital",
            "Stretched",
            "Mediocre",
            "Tall",
            "Sophisticated",
            "Wicked",
            "Spewing",
            "Happy",
            "Chewed",
            "Hurting",
            "Hairy",
            "Exposed",
            "Powerful",
            "Grunting",
            "Spectacular",
            "Forgotten",
            "Important",
            "Desperate",
            "Colonel",
            "General",
            "Jedi Master",
            "Darth",
            "Sith Lord",
            "Bounty Hunter",
            "Stormtrooper",
            "Podracer",
            "Rebel",
            "Captain",
            "Lieutenant",
            "Commander",
            "Queen",
            "Senator",
            "Emperor",
            "Padawan",
            "Jedi Knight",
            "Lord",
            "Master",
            "Count",
            "Constable",
            "Colonel",
            "General",
            "Jedi Master",
            "Darth",
            "Sith Lord",
            "Bounty Hunter",
            "Stormtrooper",
            "Podracer",
            "Rebel",
            "Captain",
            "Lieutenant",
            "Commander",
            "Queen",
            "Senator",
            "Emperor",
            "Padawan",
            "Jedi Knight",
            "Lord",
            "Master",
            "Count",
            "Constable",
            "Colonel",
            "General",
            "Jedi Master",
            "Darth",
            "Sith Lord",
            "Bounty Hunter",
            "Stormtrooper",
            "Podracer",
            "Rebel",
            "Captain",
            "Lieutenant",
            "Commander",
            "Queen",
            "Senator",
            "Emperor",
            "Padawan",
            "Jedi Knight",
            "Lord",
            "Master",
            "Count",
            "Constable",
            "Colonel",
            "General",
            "Jedi Master",
            "Darth",
            "Sith Lord",
            "Bounty Hunter",
            "Stormtrooper",
            "Podracer",
            "Rebel",
            "Captain",
            "Lieutenant",
            "Commander",
            "Queen",
            "Senator",
            "Emperor",
            "Padawan",
            "Jedi Knight",
            "Lord",
            "Master",
            "Count",
            "Constable",
            "Colonel",
            "General",
            "Jedi Master",
            "Darth",
            "Sith Lord",
            "Bounty Hunter",
            "Stormtrooper",
            "Podracer",
            "Rebel",
            "Captain",
            "Lieutenant",
            "Commander",
            "Queen",
            "Senator",
            "Emperor",
            "Padawan",
            "Jedi Knight",
            "Lord",
            "Master",
            "Count",
            "Constable");
    public static List<String> names = Arrays.asList(
            "Sim Aloo",
            "Almec",
            "Mas Amedda",
            "FodesinbeedAnnodue",
            "Apailana",
            "Ello Asty",
            "Attichitcuk",
            "AZI",
            "Walrus Man",
            "Kitster Banai",
            "Cad Bane",
            "Bane",
            "Barada",
            "Moradmin Bast",
            "BB-8",
            "Sio Bibble",
            "Depa Billaba",
            "Jar Jar Binks",
            "Temiri Blagg",
            "Bly",
            "Bobbajo",
            "Dud Bolt",
            "Lux Bonteri",
            "Mina Bonteri",
            "Borvo the Hutt",
            "Bossk",
            "BT",
            "Sora Bulq",
            "Chopper",
            "Lando Calrissian",
            "Ransolm Casterfo",
            "Chirpa",
            "Rush Clovis",
            "Kaydel Ko Connix",
            "Cordé",
            "Salacious B",
            "Arvel Crynyd",
            "Poe Dameron",
            "Vober Dand",
            "Joclad Danva",
            "Dapp",
            "Gizor Dellso",
            "Dengar",
            "Bren Derlin",
            "Ima",
            "Rinnriyin Di",
            "Tan Divo",
            "Lott Dod",
            "Daultay Dofine",
            "Lushros Dofine",
            "Dogma",
            "Dormé",
            "Cin Drallig",
            "Garven Dreis",
            "Droidbait",
            "Lok Durd",
            "Eirtaé",
            "Dineé Ellberger",
            "Ellé",
            "Caluan Ematt",
            "Embo",
            "Moralo Eval",
            "Onaconda Farr",
            "Fil",
            "Kit Fisto",
            "Fox",
            "Adi Gallia",
            "Gardulla the Hutt",
            "Yarna d",
            "Garindan",
            "Gasgano",
            "Gonk droid",
            "Gree",
            "Greedo",
            "Janus Greejatus",
            "Gregor",
            "Grummgar",
            "Gungi",
            "Nute Gunray",
            "Mars Guo",
            "Rune Haako",
            "Hardcase",
            "Rako Hardeen",
            "Gideon Hask",
            "Hevy",
            "San Hill",
            "Clegg Holdfast",
            "Tey How",
            "Huyang",
            "Inquisitor",
            "Sidon Ithano",
            "Jamillia",
            "Wes Janson",
            "Jaxxon",
            "Greeata Jendowanian",
            "Jet",
            "Dexter Jettster",
            "Tee Watt Kaa",
            "Kalani",
            "Harter Kalonia",
            "Maz Kanata",
            "Kaplan",
            "Karbin",
            "Karina",
            "Alton Kastle",
            "King Katuunko",
            "Coleman Kcaj",
            "Ki",
            "Klaatu",
            "Klik",
            "Derek Klivian",
            "Agen Kolar",
            "Plo Koon",
            "Eeth Koth",
            "Sergeant Kreel",
            "Pong Krell",
            "Black Krrsantan",
            "Satine Kryze",
            "Thane Kyrell",
            "Aito Laff",
            "Beru Lars",
            "Cliegg Lars",
            "Owen Lars",
            "Cut Lawquane",
            "Tasu Leech",
            "Xamuel Lennox",
            "Tallissan",
            "Slowen Lo",
            "Lobot",
            "Logray",
            "Lumat",
            "Shu Mai",
            "Malakili",
            "Mama the Hutt",
            "Ody Mandrell",
            "Saelt",
            "Mawhonic",
            "Droopy McCool",
            "Pharl McQuarrie",
            "Tion Medon",
            "Del Meeko",
            "Aks Moe",
            "Sly Moore",
            "Morley",
            "Mon Mothma",
            "Jobal Naberrie",
            "Pooja Naberrie",
            "Ruwee Naberrie",
            "Ryoo Naberrie",
            "Sola Naberrie",
            "Hammerhead",
            "Boss Nass",
            "Neeyutnee",
            "Enfys Nest",
            "Bazine Netal",
            "Jocasta Nu",
            "Po Nudo",
            "Nien Nunb",
            "Has Obbit",
            "Barriss Offee",
            "Hondo Ohnaka",
            "Ric Olié",
            "Savage Opress",
            "Orrimarko",
            "Ozzel",
            "Odd Ball",
            "Pablo",
            "Teemto Pagalies",
            "Jessika Pava",
            "Quarsh Panaka",
            "Casca Panzoro",
            "Reeve Panzoro",
            "Baron Papanoida",
            "Che Amanwe Papanoida",
            "Chi Eekway Papanoida",
            "Paploo",
            "Even Piell",
            "Sarco Plank",
            "Poggle the Lesser",
            "Yarael Poof",
            "Jek Tono Porkins",
            "Nahdonnis Praji",
            "Ben Quadinaros",
            "Quarrie",
            "Rabé",
            "Raddus",
            "Dak Ralter",
            "Oppo Rancisis",
            "Dodd Rancit",
            "Rappertunie",
            "Siniir Rath Velus",
            "Eneb Ray",
            "Max Rebo",
            "Ciena Ree",
            "Ree",
            "Rex",
            "Riley",
            "Rogue Squadron",
            "Romba",
            "Pagetti Rook",
            "Rotta the Hutt",
            "Rukh",
            "Sabé",
            "Saché",
            "Joph Seastriker",
            "Terrinald Screed",
            "Sebulba",
            "Aayla Secura",
            "Korr Sella",
            "Zev Senesca",
            "Echuu Shen",
            "Sifo",
            "Aurra Sing",
            "Snaggletooth",
            "Sy Snootles",
            "Osi Sobeck",
            "Greer Sonnel",
            "Sana Starros",
            "Lama Su",
            "Shriv Suurgav",
            "Gavyn Sykes",
            "Cham Syndulla",
            "Orn Free Taa",
            "Mother Talzin",
            "Wat Tambor",
            "Riff Tamson",
            "Tarfful",
            "Jova Tarkin",
            "Wilhuff Tarkin",
            "Berch Teller",
            "Teedo",
            "Mod Terrik",
            "Tessek",
            "Lor San Tekka",
            "Thanisson",
            "Thanoth",
            "Thire",
            "Thrawn",
            "Shaak Ti",
            "Paige Tico",
            "Saesee Tiin",
            "Bala",
            "Tikkes",
            "Meena Tills",
            "Quay Tolsite",
            "Bargwill Tomder",
            "Wag Too",
            "Coleman Trebor",
            "Trench",
            "Strono Tuggs",
            "Letta Turmond",
            "Longo Two",
            "Gregar Typho",
            "Ratts Tyerell",
            "Luminara Unduli",
            "Finis Valorum",
            "Nahdar Vebb",
            "Asajj Ventress",
            "Evaan Verlaine",
            "Garrick Versio",
            "Iden Versio",
            "Pre Vizsla",
            "Tulon Voidgazer",
            "Quinlan Vos",
            "Wald",
            "Warok",
            "Watto",
            "Taun We",
            "Zam Wesell",
            "Norra Wexley",
            "Snap Wexley",
            "Mace WinduWolffe",
            "Wollivan",
            "Wuher",
            "Kazuda Xiono",
            "Yaddle",
            "Yendor",
            "Joh Yowza",
            "Wullf Yularen",
            "Ziro the Hutt",
            "Zuckuss",
            "Zuvio");
    public static List<String> planets = Arrays.asList("of Argonar",
            "of Abafar",
            "of Abednedo",
            "of Absanz",
            "of Affadar",
            "of Agamar",
            "of Agaris",
            "of Agoliba",
            "of Agoliba",
            "of Ahch",
            "of Akiva",
            "of Alaris",
            "of Alderaan",
            "of Aleen",
            "of Aleen Minor",
            "of Allst Prime",
            "of Allyuen",
            "of Alpinn",
            "of Amethia Prime",
            "of Ammon IV",
            "of Anantapar",
            "of Anaxes",
            "of Andelm IV",
            "of Ando",
            "of Ando Prime",
            "of Anelsana",
            "of Ankhural",
            "of Anoat",
            "of Ansion",
            "of Antar",
            "of Anthan Prime",
            "of Aquaris",
            "of Arbiflux",
            "of Argai Minor",
            "of Aria Prime",
            "of Arieli",
            "of Arkanis",
            "of Arreyel",
            "of Artiod Minor",
            "of Arvala",
            "of Ashas Ree",
            "of Askaji",
            "of Asmeru",
            "of Asusto",
            "of Athulla",
            "of Atollon",
            "of Atrisia",
            "of Atterra Alpha",
            "of Atterra Bravo",
            "of Atterra Primo",
            "of Bakura",
            "of Balnab",
            "of Balosar",
            "of Bamayar IX",
            "of Baraan",
            "of Bardotta",
            "of Bar",
            "of Bastatha",
            "of Basteel",
            "of Batonn",
            "of Batuu",
            "of Bavva",
            "of Belderone",
            "of Bendeluum",
            "of Berzite",
            "of Bespin",
            "of Bestine IV",
            "of Bith ",
            "of Bilzen",
            "of Birren",
            "of Bogano",
            "of Bogden",
            "of Bonadan",
            "of Boonta",
            "of Boothi XII",
            "of Botajef",
            "of Bothawui",
            "of Bracca",
            "of Bray",
            "of Brentaal IV",
            "of Bri",
            "of Bromlarch",
            "of Burnin Konn",
            "of Byss ",
            "of Cadomai Prime",
            "of Calcoraan",
            "of Camson",
            "of Candovant",
            "of Cantonica",
            "of Carajam",
            "of Cardota",
            "of Carida",
            "of Carlac",
            "of Carnelion IV",
            "of Cartao",
            "of Castell",
            "of Castilon",
            "of Cato Neimoidia",
            "of Cerea",
            "of CeSai",
            "of Chaaktil",
            "of Chad",
            "of Chalacta",
            "of Chalcedon",
            "of Chal Hudda",
            "of Champala",
            "of Chandar",
            "of Chandel",
            "of Chandrila",
            "of Chasmeene",
            "of Cholganna",
            "of Christophsis",
            "of Chrona",
            "of Cianap",
            "of Clerion",
            "of Codia",
            "of Colla IV",
            "of Commenor",
            "of Cona",
            "of Concord Dawn",
            "of Corellia",
            "of Corulag",
            "of Coruscant",
            "of Cosia",
            "of Cos Secundu",
            "of Council ",
            "of Courtsilius",
            "of Coyerti",
            "of Crait",
            "of Crucival",
            "of Crul",
            "of Csilla",
            "of Cyphar",
            "of Cyrkon",
            "of Czerialus",
            "of D27Qar",
            "of Dagobah",
            "of Dallenor",
            "of Dandoran",
            "of Dantooine",
            "of Darlyn Boda",
            "of Dasoor",
            "of Dathomir",
            "of Daxam IV",
            "of Daxan Beta",
            "of The Deep",
            "of Delphon",
            "of Demir",
            "of Denash",
            "of Dennogra",
            "of Denon",
            "of Dermos",
            "of Devaron",
            "of Dhandu",
            "of Dinwa Prime",
            "of Dinzo",
            "of Dorin",
            "of Dowut",
            "of Draboon",
            "of Drahgor III",
            "of Dressel",
            "of Durkteel",
            "of Duro",
            "of Dwartii",
            "of Eadu",
            "of Edis VII",
            "of Egips",
            "of Endor ",
            "of Epiphany",
            "of Er27Kit",
            "of Eriadu",
            "of Ertegas",
            "of Espinar",
            "of Espirion",
            "of Etti IV",
            "of Eufornis Major",
            "of Eufornis Minor",
            "of Ezaraa ",
            "of Falleen ",
            "of Farhava Beta",
            "of Feenix",
            "of Felucia",
            "of Fest",
            "of Fillithar ",
            "of Firrerre",
            "of Florn",
            "of Florrum",
            "of Fondor",
            "of Frong ",
            "of Galaan",
            "of Galagolos V",
            "of Galidraan",
            "of Galidraan III",
            "of Galidraan IV",
            "of Galpos II",
            "of Galzez",
            "of Gamerong",
            "of Gamorr",
            "of Gan Moradir",
            "of Gand ",
            "of Ganthel",
            "of Garel",
            "of Gatalenta",
            "of Gentes",
            "of Geonosis",
            "of Gerrenthum",
            "of Gesaral Beta",
            "of Gigor",
            "of Giju",
            "of Gilvaanen",
            "of Glee Anselm",
            "of Gorse",
            "of Gossam ",
            "of Graf",
            "of Grange",
            "of Gravlex Med",
            "of Grizmallt",
            "of GUHL",
            "of Gutretee ",
            "of Gwongdeen",
            "of Haidoral Prime",
            "of Halcyon",
            "of Harkrova I",
            "of Harloff Minor",
            "of Haruun Kal",
            "of Hasskyn",
            "of Hays Major",
            "of Hays Minor",
            "of Helska",
            "of Hevurion",
            "of Hinari",
            "of Hirara",
            "of Hissrich",
            "of Honoghr",
            "of Horuz",
            "of Hosnian",
            "of Hosnian Prime",
            "of Hosra",
            "of Hoth",
            "of Hovun IV",
            "of Hudalla",
            "of Hynestia",
            "of Iakar",
            "of Ibaar",
            "of Iego",
            "of Ikari",
            "of Ikkrukk",
            "of Iktotchon",
            "of Iloh",
            "of Ilum",
            "of Imroosia",
            "of Imvur",
            "of Indoumodo",
            "of Insk",
            "of Inusagi",
            "of Ione",
            "of Irff",
            "of Iridonia",
            "of Irudiru",
            "of Isobe",
            "of Ison",
            "of Iskalon",
            "of Itapi Prime",
            "of Ithor",
            "of Ivarujar",
            "of Ivera X",
            "of I27vorcia Prime",
            "of Jaelen",
            "of Jakku",
            "of Jalindi",
            "of Jaresh",
            "of Jeosyn",
            "of Jeyell",
            "of Jelucan",
            "of Jhas",
            "of Jiruus",
            "of K43",
            "of Kadavo",
            "of Kaddak",
            "of Kalee",
            "of Kalevala",
            "of Kaller",
            "of Kamino",
            "of Kanzi",
            "of Kardoa",
            "of Karfeddion",
            "of Karkaris",
            "of Karlinus",
            "of Kartoosh",
            "of Kashyyyk",
            "of Keitum",
            "of Kellux",
            "of Kerev Doi",
            "of Kergans",
            "of Kerkoidia",
            "of Kessel",
            "of Kethmandi",
            "of Khorm",
            "of Kiffex",
            "of Kiffu",
            "of Kijimi",
            "of Kinrah",
            "of Kintan",
            "of Kintoni",
            "of Kirdo III",
            "of Kiros",
            "of Kirtarkin",
            "of Klatooine",
            "of Klonoid",
            "of Klytus V",
            "of Konkiv",
            "of Kooriva",
            "of Kowak",
            "of Kril",
            "of Krownest",
            "of Ktath",
            "of Kuat",
            "of Kudo",
            "of Kubindi",
            "of Kupoh",
            "of Lah",
            "of Lahn",
            "of Lannik",
            "of Lanteeb",
            "of Lanz Carpo",
            "of Lasan",
            "of Lateron",
            "of Lew",
            "of Lefrani",
            "of Lexrul",
            "of Li-Toran",
            "of Lira San",
            "of Livno III",
            "of Llanic",
            "of Lokori",
            "of Lola Sayu",
            "of Lolet",
            "of Lonera",
            "of Lothal",
            "of Lotho Minor",
            "of Luprora",
            "of Lutrillia",
            "of Lysatra",
            "of Mahranee",
            "of Makem Te",
            "of Malachor",
            "of Malastare",
            "of Malian",
            "of Malpaz",
            "of Manaan",
            "of Mandalore",
            "of Mannius Eight",
            "of Manpha",
            "of Marca",
            "of Mardona III",
            "of Maridun",
            "of Marleyvane",
            "of Mataou",
            "of Mathas",
            "of Megalox Beta",
            "of Mek",
            "of Mendavi",
            "of Merj",
            "of Merokia",
            "of Metellos",
            "of Mexeluine",
            "of Mijos",
            "of Mikkia",
            "of Milvayne",
            "of Mimban",
            "of Minfar",
            "of Mirrin Prime",
            "of Miser",
            "of Mokivj",
            "of Moldour",
            "of Mon Cala",
            "of Montross ",
            "of Moonus Mandel",
            "of Moorja",
            "of Moraband",
            "of Moraga",
            "of Mordal",
            "of Morellia",
            "of Murkhana",
            "of Mustafar",
            "of Muunilinst",
            "of Mydasos",
            "of Mygeeto",
            "of Mykapo",
            "of Naalol",
            "of Naboo",
            "of Nacon",
            "of Nacronis",
            "of Nag Ubdur",
            "of Najan",
            "of NaJedha",
            "of Najra",
            "of Nakadia",
            "of Nal Hutta",
            "of Nam Chorios",
            "of Nanth",
            "of Naraka",
            "of Nar Kanji",
            "of Narq",
            "of Necropolis",
            "of Neimoidia",
            "of Nepotis",
            "of Neral",
            "of Neskar",
            "of Nimban",
            "of Ningoth",
            "of Nixus",
            "of Noctu",
            "of Nordis Prime",
            "of Nothoiin",
            "of Noult",
            "of Numidian Prime",
            "of N27Zoth",
            "of Oba Diah",
            "of Obroa",
            "of Ocahont",
            "of Odona",
            "of Ogem",
            "of Ojom",
            "of Oktaro",
            "of Oliu",
            "of Omereth",
            "of Onderon",
            "of Ontotho",
            "of Oon",
            "of Oosalon",
            "of Ord Cestus",
            "of Ord Mantell",
            "of Ord Mynock",
            "of Ordo",
            "of Ord Pardron",
            "of Ord Radama",
            "of Ord Tiddell",
            "of Orish",
            "of Orn Kios",
            "of Orondia",
            "of Orra",
            "of Orto",
            "of Orto Plutonia",
            "of Ossus",
            "of Oulanne",
            "of Ovanis",
            "of Pamarthe",
            "of Pam",
            "of Pandem Nai",
            "of Panna",
            "of Parnassos",
            "of Pasaana",
            "of Pasher",
            "of Pastoria",
            "of Patitite Pattuna",
            "of Patrolia",
            "of Paucris Major",
            "of Pendarr III",
            "of Petrusia",
            "of Phatrong",
            "of Pheryon",
            "of Phindar",
            "of Phorsa Gedd",
            "of Pijal",
            "of Pillio",
            "of Pion",
            "of Pipada",
            "of Plexis",
            "of Plin Minor",
            "of Polis Massa",
            "of Pollillus",
            "of Polmanar",
            "of Polyneus",
            "of Ponemah Terminal",
            "of Pothor",
            "of Prefsbelt IV",
            "of Protobranch",
            "of Pujool",
            "of Qhulosk",
            "of Quarzite",
            "of Quell",
            "of Quermia",
            "of Ques",
            "of Quila",
            "of Raddan",
            "of Radhii",
            "of Rajtiri",
            "of Rekkana",
            "of Ralltiir",
            "of Rango Tan",
            "of Rattatak",
            "of Raxus",
            "of Raxus Prime",
            "of Raydonia",
            "of Raysho",
            "of Reamma",
            "of Refnu",
            "of Rendel",
            "of Retta",
            "of Rhen Var",
            "of Riflor",
            "of Rina Major",
            "of Ringo Vinda",
            "of Rinn",
            "of Rion",
            "of Riosa",
            "of Rishi",
            "of Roche ",
            "of Rodia",
            "of Rumitaka",
            "of Ruoss Minor",
            "of Ruuria",
            "of Ruusan",
            "of Ryloth",
            "of Saki ",
            "of Saleucami",
            "of Salient I",
            "of Salient II",
            "of Sammun",
            "of Samovar",
            "of Sarrish",
            "of Sarka",
            "of Satotai",
            "of Savareen",
            "of Scarif",
            "of Scipio",
            "of Secundus Ando",
            "of Sedratis",
            "of Seelos",
            "of Sembla",
            "of Serenno",
            "of Sergia",
            "of Sesid",
            "of Sevarcos",
            "of Seylott",
            "of Shadda",
            "of Sha Qarot",
            "of Shantipole",
            "of Shili",
            "of Shu-",
            "of Sibensko",
            "of Sirpar",
            "of Skako Minor",
            "of Skaradosh",
            "of Skorii",
            "of Skuhl",
            "of Sneeve",
            "of Socorro",
            "of Son-",
            "of Sorgan",
            "of Spalex",
            "of Sriluur",
            "of Starkiller Base",
            "of Sterdic IV",
            "of Stewjon",
            "of Strokill Prime",
            "of Stygeon Prime",
            "of Suba",
            "of Subterrel",
            "of Sullust",
            "of Sump",
            "of Taanab",
            "of Tah",
            "of Takobo",
            "of Takodana",
            "of Tammuz",
            "of Tamsye Prime",
            "of Tangenine",
            "of Tansyl 5",
            "of Taris",
            "of Tarsunt ",
            "of Tatooine",
            "of Taul",
            "of Tehar",
            "of Tei-",
            "of Telerath",
            "of Teralov",
            "of Teth",
            "of Tevel",
            "of Thabeska",
            "of Theron",
            "of Thisspias",
            "of Tholoth",
            "of Thrad",
            "of Thune",
            "of Thustra",
            "of Tibrin",
            "of Tiferep Major",
            "of Tinnel IV",
            "of Tirahnn",
            "of Tokmia",
            "of Toola",
            "of Toprawa",
            "of Tosste",
            "of Touksingal",
            "of Toydaria",
            "of Trandosha",
            "of Trasse",
            "of Trionak",
            "of Trivar II",
            "of Trogan",
            "of Troiken",
            "of Tsevuka",
            "of Tureen VII",
            "of Tund",
            "of Twon Ketee",
            "of Tyegin",
            "of Tynna",
            "of Tython",
            "of Uba",
            "of Ubardia",
            "of Ubduria",
            "of Uchinao",
            "of Ukio",
            "of Umbara",
            "of Uquine",
            "of Uro",
            "of Ushruu",
            "of Utapau",
            "of Uyter",
            "of Vallt",
            "of Vandor",
            "of Vanqor",
            "of Vardos",
            "of Vashka",
            "of Vassek",
            "of Velusia",
            "of Vendaxa",
            "of Vernid",
            "of Veros",
            "of Vertseth",
            "of Vetine",
            "of Viamarr",
            "of Vir Aphshire",
            "of Virujansi",
            "of Vixnix",
            "of Vjun",
            "of Vodran",
            "of Vorlag",
            "of Vrogas Vas",
            "of Vulpter",
            "of Vurdon Ka",
            "of Vyndal",
            "of Wadi Raffa",
            "of Watassay",
            "of Wayland",
            "of Wecacoe",
            "of Wellspring of Life",
            "of Wobani",
            "of Whiforla II",
            "of Wrea",
            "of Wynkahthu",
            "of Xagobah",
            "of Xala",
            "of Xendek",
            "of Xirl",
            "of Yar Togna",
            "of Yarma",
            "of Yavin",
            "of Ylesia",
            "of Yout",
            "of Zastiga",
            "of Zeffo",
            "of Zhanox",
            "of Zoh",
            "of Zoph",
            "of Zolan",
            "of Zygerria",
            "of Zyzar");
}
